sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
      
    packages:
      - cmake
      - cmake-data
      - g++-9
      - libboost-all-dev
      - valgrind
      - libperlio-gzip-perl
      - libjson-perl


before_install:
  - export CXX="g++-9"
  - export CC="gcc-9"
  - g++-9 --version

install:
  - ./buildDeps.sh
  - pip install --user cpp-coveralls
  
script: 
  - ./buildFromDeps.sh
  - cd Build
  - make test
  - ctest -T Memcheck
  - cd ..
  - GCOV="gcov-9" LCOV_FILTERS="$PWD/src/cfgClean.cpp $PWD/src/processAds.cpp" ./deps/CMakeUtils/travis/doCoverage.sh
